-- This script was generated by the ERD tool in pgAdmin 4.
-- Please log an issue at https://github.com/pgadmin-org/pgadmin4/issues/new/choose if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public."Sales transaction"
(
    transaction_id integer NOT NULL,
    date date,
    "time" time with time zone,
    sales_id integer NOT NULL,
    PRIMARY KEY (transaction_id)
);

CREATE TABLE IF NOT EXISTS public."Product"
(
    product_id integer NOT NULL,
    product_name character varying NOT NULL,
    description character varying,
    price character varying,
    PRIMARY KEY (product_id)
);

CREATE TABLE IF NOT EXISTS public.sales_detail
(
    sales_id integer NOT NULL,
    sales_outlet_id integer,
    staff_id integer,
    customer_id integer,
    product_id integer NOT NULL,
    quantity integer,
    price character varying,
    PRIMARY KEY (sales_id)
);

CREATE TABLE IF NOT EXISTS public.product_type
(
    product_name character varying NOT NULL,
    product_type character varying,
    product_category character varying,
    PRIMARY KEY (product_name)
);

ALTER TABLE IF EXISTS public."Sales transaction"
    ADD CONSTRAINT sales_id FOREIGN KEY (sales_id)
    REFERENCES public.sales_detail (sales_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public."Product"
    ADD CONSTRAINT product_name FOREIGN KEY (product_name)
    REFERENCES public.product_type (product_name) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;


ALTER TABLE IF EXISTS public.sales_detail
    ADD CONSTRAINT product_id FOREIGN KEY (product_id)
    REFERENCES public."Product" (product_id) MATCH SIMPLE
    ON UPDATE NO ACTION
    ON DELETE NO ACTION
    NOT VALID;

END;